/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 *  * Class:     HelloJNI
 *   * Method:    sayHello
 *    * Signature: ()V
 *     */
JNIEXPORT void JNICALL Java_com_kylin_jvm_jni_HelloJNI_sayHello
  (JNIEnv *, jobject);
 
#ifdef __cplusplus
}
#endif
#endif
