/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_lab_TestClass */

#ifndef _Included_com_kylin_jvm_lab_TestClass
#define _Included_com_kylin_jvm_lab_TestClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 *  * Class:     sample_lab_TestClass
 *   * Method:    printHello
 *    * Signature: ()V
 *     */
JNIEXPORT void JNICALL Java_com_kylin_jvm_lab_TestClass_printHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
