Basic conception, instruction
-----------------------------

link:jvm-architecture.asciidoc[HotSpot JVM Architecture]

link:oracle_JVM_memory_management.asciidoc[Oracle JVM Memory Management]

link:gc.asciidoc[Java Garbage Collection Basics]


JVM OPTS & Commands
-------------------

Enable GC log
+++++++++++++

----
-verbose:gc -Xloggc:gc.log
-verbose:gc -Xloggc:gc.log -XX:+PrintGCDetails
-verbose:gc -Xloggc:gc.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps
----

link:gc-log-demo.asciidoc[GC Log Demo]

link:gc.asciidoc[What's GC]

Enable heap dump
++++++++++++++++

----
-XX:+HeapDumpOnOutOfMemoryError
----

Heap Reference
++++++++++++++

* initial java heap size
----
-Xms
----

* maximum java heap size
----
-Xmx
----

* the size of the heap for the young generation
----
-Xmn
----

Perm Reference
++++++++++++++


Enable jconsole
+++++++++++++++

* jconsole monitor j2se app(including JMX MBean monitor)
----
-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
----

* jconsole monitor j2se app(Only monitor memory and threads)
----
-Dcom.sun.management.jmxremote
----

* jconsole monitor JBoss 6 and previous version JBoss
----
-Djboss.platform.mbeanserver
----

Use jmap
++++++++

* print java heap summary
----
jmap -heap <PID>
----

link:heap-summary-demo[Heap Summary Demo]

* generate heap dump(Linux 32)
----
jmap -dump:format=b,file=heap.hprof JAVA_PID
----

* generate heap dump(Linux 64)
----
jmap -J-d64 -dump:format=b,file=heap.hprof JAVA_PID
----

* generate heap dump(Windows)
----
jmap -dump:format=b,file=heap.hprof JAVA_PID
----





Useful Link
-----------

* JVM OPT: http://www.oracle.com/technetwork/java/javase/tech/vmoptions-jsp-140102.html
* Solving common Java EE performance problems: http://www.javaworld.com/javaworld/jw-06-2006/jw-0619-tuning.html
* Java® Virtual Machine Specification: http://docs.oracle.com/javase/specs/jvms/se7/html/
* Java Garbage Collection Tutorial: http://www.oracle.com/webfolder/technetwork/tutorials/obe/java/gc01/index.html
* Tuning JVM: http://www.oracle.com/webfolder/technetwork/tutorials/obe/java/gc01/index.html 


